### PR TITLE
Hashim

### PR DESCRIPTION
**Pull request by Hashim-ca**
**Stat Class:** Provides event statistics such as total events and attendee counts.
**EventManager Class:** Central management of events, including adding, updating, and removing events, and managing attendees.
**Event Class:** Updates for detailed event management, including attendee list management and event detail updates.

### CODE REVIEW

**Comment by MSNanda515** [comment]
Use sub-packages to organize different kinds of classes. For example, most of the added classes look like they would go in the models package if you were to follow the MVC architecture.

**Comment by Hashim-ca** [comment]
> Use sub-packages to organize different kinds of classes. For example, most of the added classes look like they would go in the models package if you were to follow the MVC architecture.

I am not sure if we have a model package created in the main yet, can you elaborate what you meant by sub-packaged

**Review by FaiqueAhmaduAlberta — APPROVED** [review]
Ye looks good now

**Review by sqiggles — APPROVED** [review]
looks good

**Pull request merged**
