### PR TITLE
Profile Picture Generation First Draft

### PR DESCRIPTION
**Pull request by tsteele1**
Finished deterministic profile picture generation and integrated it into the app.

### CODE REVIEW

**Review by sqiggles — DISMISSED** [review]
epic

**Review by farhamachiwala02 — COMMENTED** [review]
why change this from imageURL to imageURI? User newUser = new User(firstName, lastName, parseLong(phoneStr), email, geo, imageURI);

**Review by farhamachiwala02 — APPROVED** [review]
works!

**Review by znorth1 — APPROVED** [review]
farha said it was working

**Pull request closed without merging**
